import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UsersProvider } from "@/context/users";
import { ItemsProvider } from "@/context/items";
import { ThemeProvider } from "@/components/themeprovider";
import { AuthProvider } from "@/context/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <UsersProvider>
            <ItemsProvider>
              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
              >
                {children}
              </ThemeProvider>
            </ItemsProvider>
          </UsersProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
